name: 🚀 Adding the commit to the next release
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4.3.0
        with:
          # We can't use GITHUB_TOKEN here because, github actions can't trigger actions
          # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # So this is a personal access token
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
